on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: git@github.com:Guilherme-Phellippe/api-node-temsabor.git

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ../../app/server
            git config --global --add safe.directory /app/server
            git pull
            sudo npm i
            sudo npm run build
            pm2 restart temsabor-server

